spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER_NAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

# AWS config
aws:
  region: us-east-1
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:http://localhost:4566/000000000000/credinya-notifications}
    notification-queue-url: ${AWS_SQS_NOTIFICATION_QUEUE_URL}
    capacity-queue-url: ${AWS_SQS_CAPACITY_QUEUE_URL}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID:fakeAccessKey}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:fakeSecretKey}

app:
  sqs:
    enabled: ${SQS_ENABLED:false}

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
