server:
  port: 8080

spring:
  application:
    name: loan-service
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

user:
  service:
    base-url: http://user-service:8081