spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: postgres
    password: 123456789

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "TBfdZLz1jcl6o/+vVsfgYjYq6ZQHIeGvuxG4C5mtI7IeNoSvxScVzCt6EXwptyfbjUXayqQ9sZupvlLMDlg3FA=="
  expiration-ms: 3600000