spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

  aws:
    region: us-east-1 # Cambia según tu región preferida
    sqs:
      queue-url: ${AWS_SQS_QUEUE_URL:http://localhost:4566/000000000000/credinya-notifications} # URL para LocalStack o AWS real
    credentials:
      access-key-id: ${AWS_ACCESS_KEY_ID:fakeAccessKey} # Usará placeholders para desarrollo
      secret-access-key: ${AWS_SECRET_ACCESS_KEY:fakeSecretKey}

  app:
    sqs:
      enabled: ${SQS_ENABLED:false} # Bandera para activar/desactivar el envío real a SQS


cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}
