server:
  port: 8080

spring:
  application:
    name: loan-service
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

user:
  service:
    base-url: http://user-service:8081

# AWS
aws:
  region: us-east-1
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL}
    notification-queue-url: ${AWS_SQS_NOTIFICATION_QUEUE_URL}
    capacity-queue-url: ${AWS_SQS_CAPACITY_QUEUE_URL}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}

app:
  sqs:
    enabled: true